# Bazel BUILD file for W5500 code from WIZnet.
# NOTE: Needs much work to support building on an arbitrary machine.

load(
    "//experimental/users/jamessynge/arduino/mcucore/extras/bazel:arduino_cc_library.bzl",
    "arduino_cc_library",
)

arduino_cc_library(
    name = "util",
    hdrs = ["util.h"],
)
